context:
  version: 1.3.6

package:
  name: choose-rust
  version: ${{ version }}

source:
  url: https://github.com/theryangeary/choose/archive/v${{ version }}.tar.gz
  sha256: 3d28dc39339dbf5c6197eb803b199661d6d261bc827c194b31b19d1afad01487

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - choose --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Human-friendly and fast alternative to cut and (sometimes) awk
  homepage: https://github.com/theryangeary/choose
  repository: https://github.com/theyrangeary/choose

extra:
  recipe-maintainers:
    - danielnachun
